@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class, androidx.compose.material3.ExperimentalMaterial3ExpressiveApi::class)
package com.sahil.mindrelay

import android.Manifest
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.speech.RecognizerIntent
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.interaction.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import java.text.SimpleDateFormat
import java.util.*

private sealed interface S {
    data object Home:S; data object Quick:S; data object Inbox:S; data class Capture(val id:Long):S
    data object Projects:S; data class Project(val id:Long):S; data class Session(val id:Long):S; data class End(val id:Long):S
    data object Memories:S; data class Memory(val id:Long):S; data class NewMemory(val capture:Long?=null,val session:Long?=null):S
    data object NewProject:S; data object Search:S; data object Settings:S; data object Backup:S
}
private enum class T{Right,Left,Up,Down,Fade,Expand}

@Composable fun MindRelayApp(db:MindRelayDb){
    val ctx=LocalContext.current; val prefs=remember{ctx.getSharedPreferences("mindrelay",Context.MODE_PRIVATE)}
    var mode by remember{mutableStateOf(prefs.getString("theme","System")!!)}; var rev by remember{mutableIntStateOf(0)}
    var screen by remember{mutableStateOf<S>(S.Home)}; var stack by remember{mutableStateOf(listOf<S>())}; var anim by remember{mutableStateOf(T.Fade)}
    val dark=when(mode){"Dark"->true;"Light"->false;else->isSystemInDarkTheme()}
    MaterialExpressiveTheme(colorScheme=if(dark)DarkColors() else LightColors(),typography=MindRelayTypography(),motionScheme=MotionScheme.expressive()){
        fun go(s:S,t:T=T.Right){stack=stack+screen;screen=s;anim=t}; fun root(s:S){stack=emptyList();screen=s;anim=T.Fade}; fun back(){if(stack.isNotEmpty()){screen=stack.last();stack=stack.dropLast(1);anim=T.Left}}
        BackHandler(enabled=stack.isNotEmpty(),onBack=::back)
        AnimatedContent(screen,transitionSpec={when(anim){T.Right->slideInHorizontally{it}+fadeIn() togetherWith slideOutHorizontally{-it/3}+fadeOut();T.Left->slideInHorizontally{-it/3}+fadeIn() togetherWith slideOutHorizontally{it}+fadeOut();T.Up->slideInVertically{it}+fadeIn() togetherWith slideOutVertically{-it/3}+fadeOut();T.Down->slideInVertically{-it/3}+fadeIn() togetherWith slideOutVertically{it}+fadeOut();T.Expand->scaleIn(initialScale=.92f)+fadeIn() togetherWith scaleOut(targetScale=.98f)+fadeOut();T.Fade->fadeIn() togetherWith fadeOut()}},label="nav"){
            when(it){
                S.Home->Home(db,rev,::root,::go){rev++}; S.Quick->Quick(db,::back,::root){rev++}; S.Inbox->Inbox(db,rev,::root,::go,::back){rev++};
                is S.Capture->CaptureDetail(db,it.id,::back,::go){rev++}; S.Projects->Projects(db,rev,::root,::go){rev++}; is S.Project->ProjectDetail(db,it.id,rev,::back,::go){rev++};
                is S.Session->SessionScreen(db,it.id,rev,::back,::go){rev++}; is S.End->EndSession(db,it.id,::back,::go){rev++}; S.Memories->Memories(db,rev,::root,::go){rev++}; is S.Memory->MemoryDetail(db,it.id,rev,::back,::go){rev++};
                is S.NewMemory->NewMemoryScreen(db,it.capture,it.session,::back,::go){rev++}; S.NewProject->NewProject(db,::back,::go); S.Search->Search(db,rev,::root,::go,::back); S.Settings->Settings(db,::back,::go,mode,{mode=it;prefs.edit().putString("theme",it).apply()}); S.Backup->Backup(db,::back){rev++}
            }
        }
    }
}

@Composable private fun Header(title:String,back:()->Unit={},actions:@Composable RowScope.()->Unit={})=TopAppBar(title={Text(title)},navigationIcon={if(title!="MindRelay")IconButton(back){Icon(Icons.Rounded.ArrowBack,"Back")}},actions=actions)
@Composable private fun Section(t:String)=Text(t,style=MaterialTheme.typography.titleMediumEmphasized)
@Composable private fun Chips(items:List<String>,selected:String,on:(String)->Unit)=LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){items(items){x->FilterChip(x==selected,{on(x)},{Text(x)},leadingIcon=if(x==selected)({Icon(Icons.Rounded.Check,null,Modifier.size(16.dp))})else null)}}
@Composable private fun AddFab(on:()->Unit,large:Boolean=false,tonal:Boolean=false){val bg=if(tonal)MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.primary;val fg=if(tonal)MaterialTheme.colorScheme.onPrimaryContainer else MaterialTheme.colorScheme.onPrimary;if(large)LargeFloatingActionButton(on,shape=RoundedCornerShape(28.dp),containerColor=bg,contentColor=fg){Icon(Icons.Rounded.Add,"Add",Modifier.size(32.dp))}else FloatingActionButton(on,shape=RoundedCornerShape(16.dp),containerColor=bg,contentColor=fg){Icon(Icons.Rounded.Add,"Add")}}
@Composable private fun Nav(sel:S,root:(S)->Unit)=NavigationBar(containerColor=MaterialTheme.colorScheme.surfaceContainer){listOf(Triple(S.Home,Icons.Rounded.Home,"Home"),Triple(S.Inbox,Icons.Rounded.Inbox,"Inbox"),Triple(S.Projects,Icons.Rounded.FolderOpen,"Projects"),Triple(S.Memories,Icons.Rounded.Bookmark,"Memories"),Triple(S.Search,Icons.Rounded.Search,"Search")).forEach{(s,i,l)->NavigationBarItem(selected=sel==s,onClick={root(s)},icon={Icon(i,l)},label={Text(l)})}}
@Composable private fun Item(index:Int,count:Int,icon:androidx.compose.ui.graphics.vector.ImageVector,title:String,support:String,on:()->Unit={}){val shape=when{count==1->RoundedCornerShape(28.dp);index==0->RoundedCornerShape(28.dp,28.dp,8.dp,8.dp);index==count-1->RoundedCornerShape(8.dp,8.dp,28.dp,28.dp);else->RoundedCornerShape(8.dp)};val src=remember{MutableInteractionSource()};val p by src.collectIsPressedAsState();Surface(shape=shape,color=MaterialTheme.colorScheme.surfaceContainerLow,modifier=Modifier.fillMaxWidth().height(72.dp).graphicsLayer(scaleX=if(p).985f else 1f,scaleY=if(p).985f else 1f).clickable(src,null,role=Role.Button,onClick=on)){Row(Modifier.fillMaxSize().padding(12.dp),verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(40.dp),CircleShape,color=MaterialTheme.colorScheme.primaryContainer){Box(contentAlignment=Alignment.Center){Icon(icon,null,tint=MaterialTheme.colorScheme.onPrimaryContainer)}};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(title,maxLines=1,overflow=TextOverflow.Ellipsis);Text(support,color=MaterialTheme.colorScheme.onSurfaceVariant,maxLines=1,overflow=TextOverflow.Ellipsis)}}}}
@Composable private fun Empty(t:String,b:String,icon:androidx.compose.ui.graphics.vector.ImageVector)=Column(Modifier.fillMaxWidth().padding(40.dp),horizontalAlignment=Alignment.CenterHorizontally){Surface(Modifier.size(72.dp),CircleShape,color=MaterialTheme.colorScheme.primaryContainer){Box(contentAlignment=Alignment.Center){Icon(icon,null,tint=MaterialTheme.colorScheme.onPrimaryContainer)}};Spacer(Modifier.height(16.dp));Text(t,style=MaterialTheme.typography.titleLargeEmphasized,textAlign=TextAlign.Center);Spacer(Modifier.height(8.dp));Text(b,color=MaterialTheme.colorScheme.onSurfaceVariant,textAlign=TextAlign.Center)}
@Composable private fun CardX(head:String?=null,body:String,bg:Color=MaterialTheme.colorScheme.surfaceContainerHighest,on:(()->Unit)?=null)=Card(onClick={on?.invoke()},enabled=on!=null,shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=bg),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(20.dp)){head?.let{Text(it,style=MaterialTheme.typography.titleMediumEmphasized);Spacer(Modifier.height(4.dp))};Text(body)}}

@Composable private fun Home(db:MindRelayDb,rev:Int,root:(S)->Unit,go:(S,T)->Unit,refresh:()->Unit){val p=remember(rev){db.projects("Active")}.firstOrNull();val tasks=remember(rev){db.tasks().filter{!it.completed}.take(2)};val revisit=remember(rev){db.memories().filter{it.revisitAt!=null}.sortedBy{it.revisitAt}.take(2)};Scaffold(topBar={TopAppBar(title={Text("MindRelay")},actions={IconButton({go(S.Settings)}){Icon(Icons.Rounded.Settings,"Settings")}})},floatingActionButton={AddFab({go(S.Quick,T.Expand)},true)},bottomBar={Nav(S.Home,root)}){pad->LazyColumn(Modifier.padding(pad).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp),contentPadding=PaddingValues(bottom=96.dp)){item{Text("What should Future Me know right now?",style=MaterialTheme.typography.headlineSmallEmphasized)};item{CardX("Continue",p?.let{"${it.name}\n\n${it.currentState.ifBlank{"No current state yet."}}\n\nNext: ${it.nextAction.ifBlank{"Define the next concrete action"}}"}?:"Nothing in progress yet. Create a project to give Future You context.",MaterialTheme.colorScheme.primaryContainer,{if(p==null)go(S.NewProject,T.Up)else go(S.Project(p.id))})};item{Section("Next actions")};if(tasks.isEmpty())item{Text("No tasks yet.",color=MaterialTheme.colorScheme.onSurfaceVariant)}else items(tasks){x->Item(0,1,Icons.Rounded.CheckCircle,x.title,db.project(x.projectId?:0)?.name?:"Personal",{db.setTaskComplete(x.id,true);refresh()})};item{CardX("Inbox","${db.captures().size} items waiting to be sorted",on={go(S.Inbox)})};item{Section("Revisit soon")};if(revisit.isEmpty())item{Text("No revisit dates scheduled.",color=MaterialTheme.colorScheme.onSurfaceVariant)}else items(revisit){m->Item(0,1,Icons.Rounded.EventRepeat,m.title,m.type,{go(S.Memory(m.id))})}}}}

@Composable private fun Quick(db:MindRelayDb,back:()->Unit,root:(S)->Unit,refresh:()->Unit){val c=LocalContext.current;val prefs=remember{c.getSharedPreferences("mindrelay",0)};var text by rememberSaveable{mutableStateOf(prefs.getString("draft","")!!)};var type by rememberSaveable{mutableStateOf("Idea")};var project by rememberSaveable{mutableLongStateOf(0)};var voice by rememberSaveable{mutableStateOf(false)};val speech=rememberLauncherForActivityResult(ActivityResultContracts.StartActivityForResult()){r->r.data?.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS)?.firstOrNull()?.let{ text=(text+" "+it).trim();voice=true;prefs.edit().putString("draft",text).apply()}};val perm=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){if(it)speech.launch(Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM))};fun mic(){if(ContextCompat.checkSelfPermission(c,Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)speech.launch(Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM))else perm.launch(Manifest.permission.RECORD_AUDIO)};val projects=remember{db.projects("Active")};Scaffold(topBar={TopAppBar(title={Text("Quick Capture")},navigationIcon={IconButton(back){Icon(Icons.Rounded.Close,"Close")}})}){pad->Column(Modifier.verticalScroll(rememberScrollState()).padding(pad).padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("What's on your mind?",style=MaterialTheme.typography.headlineSmallEmphasized);Text("Get it out now. Sort it later.",color=MaterialTheme.colorScheme.onSurfaceVariant);OutlinedTextField(text,{text=it;prefs.edit().putString("draft",it).apply()},Modifier.fillMaxWidth().height(180.dp),label={Text("Type a thought...")},leadingIcon={IconButton(::mic){Icon(Icons.Rounded.Mic,"Microphone")}},supportingText={Text("Saved locally immediately. No account required.")});Chips(listOf("Idea","To-do","Question"),type){type=it};Item(0,1,Icons.Rounded.FolderOpen,"Link to project (optional)",projects.firstOrNull{it.id==project}?.name?:"None"){project=projects.firstOrNull()?.id?:0};Text("🔒 Stays on your device. No cloud, no account.",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(3.dp)){Button({if(text.isNotBlank()){db.insertCapture(type,text,project.takeIf{it!=0L},null,voice);text="";voice=false;prefs.edit().remove("draft").apply();refresh()}},Modifier.weight(1f),shape=RoundedCornerShape(28.dp,8.dp,8.dp,28.dp)){Text("Save & keep writing")};Button({if(text.isNotBlank())db.insertCapture(type,text,project.takeIf{it!=0L},null,voice);text="";prefs.edit().remove("draft").apply();refresh();root(S.Home)},Modifier.weight(1f),shape=RoundedCornerShape(8.dp,28.dp,28.dp,8.dp)){Text("Save to Inbox")}}}}}

@Composable private fun Inbox(db:MindRelayDb,rev:Int,root:(S)->Unit,go:(S,T)->Unit,back:()->Unit,refresh:()->Unit){var f by rememberSaveable{mutableStateOf("All")};val xs=remember(rev,f){db.captures(f.takeUnless{it=="All"})};Scaffold(topBar={Header("Inbox",back)},floatingActionButton={AddFab({go(S.Quick,T.Expand)})},bottomBar={Nav(S.Inbox,root)}){p->LazyColumn(Modifier.padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(3.dp),contentPadding=PaddingValues(bottom=96.dp)){item{Chips(listOf("All","Ideas","To-dos","Questions","Voice"),f){f=it}};if(xs.isEmpty())item{Empty("Inbox is clear","Captured thoughts will stay here until you triage them.",Icons.Rounded.Inbox)}else itemsIndexed(xs){i,x->Item(i,xs.size,captureIcon(x.type,x.isVoice),x.body,"${x.type} · ${ago(x.createdAt)}",{go(S.Capture(x.id))})}}}}
private fun captureIcon(t:String,v:Boolean)=when{v->Icons.Rounded.Mic;t=="Idea"->Icons.Rounded.Lightbulb;t=="To-do"->Icons.Rounded.CheckBox;t=="Question"->Icons.Rounded.Help;else->Icons.Rounded.Restaurant}

@Composable private fun CaptureDetail(db:MindRelayDb,id:Long,back:()->Unit,go:(S,T)->Unit,refresh:()->Unit){val x=db.capture(id)?:return;Scaffold(topBar={Header("Capture",back,actions={IconButton({db.archiveCapture(id);refresh();back()}){Icon(Icons.Rounded.Archive,"Archive")}})}){p->Column(Modifier.verticalScroll(rememberScrollState()).padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){AssistChip({},label={Text(x.type)});Text("Captured ${ago(x.createdAt)} · ${if(x.isVoice)"voice entry"else"text entry"}",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);CardX(x.type,x.body);Item(0,1,Icons.Rounded.FolderOpen,"Linked project",x.projectId?.let{db.project(it)?.name}?:"None");Item(0,1,Icons.Rounded.Schedule,"Linked session",x.sessionId?.let{db.session(it)?.title}?:"None");Section("Convert to");listOf(Triple("Memory","Durable knowledge Future You can find",Icons.Rounded.Bookmark),Triple("Project note","Attach to a project or current session",Icons.Rounded.FolderOpen),Triple("Task","Create a secondary to-do item",Icons.Rounded.CheckBox),Triple("Archive","Remove from active inbox",Icons.Rounded.Archive)).forEachIndexed{i,a->Item(i,4,a.third,a.first,a.second,{when(a.first){"Memory"->go(S.NewMemory(id,x.sessionId),T.Up);"Project note"->x.projectId?.let{go(S.Project(it))};"Task"->{db.insertTask(x.body,x.projectId);db.archiveCapture(id);refresh();back()};else->{db.archiveCapture(id);refresh();back()}}})}}}}

@Composable private fun Projects(db:MindRelayDb,rev:Int,root:(S)->Unit,go:(S,T)->Unit,refresh:()->Unit){var st by rememberSaveable{mutableStateOf("Active")};val ps=remember(rev,st){db.projects(st)};Scaffold(topBar={Header("Projects")},floatingActionButton={AddFab{go(S.NewProject,T.Up)}},bottomBar={Nav(S.Projects,root)}){p->LazyColumn(Modifier.padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp),contentPadding=PaddingValues(bottom=96.dp)){item{Chips(listOf("Active","Paused","Done"),st){st=it}};if(ps.isEmpty())item{Empty("No $st projects","Create a project to give Future You a stable context.",Icons.Rounded.FolderOpen)}else items(ps){x->Card(onClick={go(S.Project(x.id))},shape=RoundedCornerShape(20.dp),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceContainerHighest),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(20.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text(x.name,style=MaterialTheme.typography.titleMediumEmphasized,modifier=Modifier.weight(1f));AssistChip({},label={Text(x.status)})};Spacer(Modifier.height(4.dp));Text("${db.sessions(x.id).size} sessions · ${ago(x.lastWorkedAt)}",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(6.dp));Text(x.currentState.ifBlank{"No current state yet."});Spacer(Modifier.height(4.dp));Text("Next: ${x.nextAction.ifBlank{"Define the next concrete action"}}",color=MaterialTheme.colorScheme.onSurfaceVariant)}}}}}}}
