@file:OptIn(androidx.compose.material3.ExperimentalMaterial3Api::class, androidx.compose.material3.ExperimentalMaterial3ExpressiveApi::class)
package com.sahil.mindrelay

import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import java.text.SimpleDateFormat
import java.util.*
import org.json.JSONObject

@Composable private fun ProjectDetail(db:MindRelayDb,id:Long,rev:Int,back:()->Unit,go:(S,T)->Unit,refresh:()->Unit){val p=db.project(id)?:return;val sessions=remember(rev,id){db.sessions(id)};Scaffold(topBar={Header(p.name,back)},containerColor=MaterialTheme.colorScheme.surface){pad->Column(Modifier.verticalScroll(rememberScrollState()).padding(pad).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){AssistChip({},label={Text(p.status)});CardX("Current state",p.currentState.ifBlank{"Add what is true right now."});CardX("Next action",p.nextAction.ifBlank{"Add one concrete next step."},MaterialTheme.colorScheme.tertiaryContainer);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(3.dp)){Button({val a=sessions.firstOrNull{it.status=="Active"}?.id?:db.startSession(id,"Session ${sessions.size+1}");refresh();go(S.Session(a))},Modifier.weight(1f),shape=RoundedCornerShape(28.dp,8.dp,8.dp,28.dp)){Text("Resume session")};Button({db.updateProject(p.copy(goalNotes=(p.goalNotes+"\nProject note").trim()));refresh()},Modifier.weight(1f),colors=ButtonDefaults.buttonColors(containerColor=MaterialTheme.colorScheme.secondaryContainer,contentColor=MaterialTheme.colorScheme.onSecondaryContainer),shape=RoundedCornerShape(8.dp,28.dp,28.dp,8.dp)){Text("Add note")}};Section("Recent sessions");sessions.take(10).forEachIndexed{i,s->Item(i,sessions.size.coerceAtMost(10),Icons.Rounded.Schedule,s.title,"${s.status} · ${duration(s.startedAt,s.endedAt)}"){go(S.Session(s.id))}};Section("Linked memories");db.memories().filter{it.projectId==id}.forEach{m->Item(0,1,Icons.Rounded.Bookmark,m.title,m.type){go(S.Memory(m.id))}}}}}

@Composable private fun SessionScreen(db:MindRelayDb,id:Long,rev:Int,back:()->Unit,go:(S,T)->Unit,refresh:()->Unit){val s=db.session(id)?:return;val p=db.project(s.projectId);val e=remember(rev,id){db.sessionEntries(id)};var tab by rememberSaveable{mutableStateOf("Log")};var add by remember{mutableStateOf(false)};val filtered=e.filter{tab=="Log"||it.kind==when(tab){"Discoveries"->"Discovery";"Questions"->"Question";else->tab}};Scaffold(topBar={Header("Session ${s.id}",back)},floatingActionButton={AddFab({add=true},tonal=true)}){pad->LazyColumn(Modifier.padding(pad).padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp),contentPadding=PaddingValues(bottom=96.dp)){item{Text(p?.name?:"Project")};item{AssistChip({},label={Text("${s.status} · ${duration(s.startedAt,s.endedAt)}")})};item{Chips(listOf("Log","Discoveries","Questions"),tab){tab=it}};if(filtered.isEmpty())item{Empty("Nothing logged yet","Use + to record the work as it happens.",Icons.Rounded.Notes)}else items(filtered){x->Item(0,1,entryIcon(x.kind),x.body,"${SimpleDateFormat("HH:mm",Locale.getDefault()).format(Date(x.createdAt))} · ${x.kind}")};item{CardX("Current next action",p?.nextAction?.ifBlank{"Add a next action"}?:"Add a next action")};item{Button({go(S.End(id),T.Up)},Modifier.fillMaxWidth().height(56.dp),shape=RoundedCornerShape(28.dp)){Icon(Icons.Rounded.Flag,null);Spacer(Modifier.width(8.dp));Text("End session & write handoff")}}}};if(add)AddEntrySheet(db,id,{add=false;refresh()})}
private fun entryIcon(k:String)=when(k){"Problem"->Icons.Rounded.Warning;"Discovery"->Icons.Rounded.Lightbulb;"Question"->Icons.Rounded.Help;"Decision"->Icons.Rounded.Flag;"Task"->Icons.Rounded.ShoppingCart;else->Icons.Rounded.Notes}
@Composable private fun AddEntrySheet(db:MindRelayDb,id:Long,close:()->Unit){var k by rememberSaveable{mutableStateOf("Note")};var body by rememberSaveable{mutableStateOf("")};ModalBottomSheet(close){Column(Modifier.fillMaxWidth().padding(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Add to session",style=MaterialTheme.typography.titleLargeEmphasized);Chips(listOf("Note","Discovery","Question","Decision","Task"),k){k=it};OutlinedTextField(body,{body=it},Modifier.fillMaxWidth(),label={Text("What happened?")},minLines=3);Button(body.isNotBlank(),{db.addSessionEntry(id,k,body);close()},Modifier.fillMaxWidth()){Text("Add entry")};Spacer(Modifier.height(12.dp))}}}

@Composable private fun EndSession(db:MindRelayDb,id:Long,back:()->Unit,go:(S,T)->Unit,refresh:()->Unit){val s=db.session(id)?:return;var c by rememberSaveable{mutableStateOf("")};var d by rememberSaveable{mutableStateOf("")};var u by rememberSaveable{mutableStateOf("")};var n by rememberSaveable{mutableStateOf(db.project(s.projectId)?.nextAction?:"")};var promote by rememberSaveable{mutableStateOf(true)};Scaffold(topBar={Header("End session",back)}){pad->Column(Modifier.verticalScroll(rememberScrollState()).padding(pad).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Write a handoff for Future You.",style=MaterialTheme.typography.titleMediumEmphasized);OutlinedTextField(c,{c=it},Modifier.fillMaxWidth(),label={Text("What did I complete?")},minLines=2);OutlinedTextField(d,{d=it},Modifier.fillMaxWidth(),label={Text("What did I discover?")},minLines=2);OutlinedTextField(u,{u=it},Modifier.fillMaxWidth(),label={Text("What is unresolved?")},minLines=2);OutlinedTextField(n,{n=it},Modifier.fillMaxWidth(),label={Text("Single next action")},minLines=2);Row(verticalAlignment=Alignment.CenterVertically){Checkbox(promote,{promote=it});Text("Promote the discovery above to Memory")};Button(n.isNotBlank()||c.isNotBlank()||d.isNotBlank()||u.isNotBlank(),{db.finishSessionWithHandoff(id,s.projectId,c,d,u,n,promote);refresh();go(S.Project(s.projectId),T.Down)},Modifier.fillMaxWidth().height(56.dp),shape=RoundedCornerShape(28.dp)){Text("Save handoff & end session")}}}}

@Composable private fun Memories(db:MindRelayDb,rev:Int,root:(S)->Unit,go:(S,T)->Unit,refresh:()->Unit){var f by rememberSaveable{mutableStateOf("All")};var q by rememberSaveable{mutableStateOf("")};val ms=remember(rev,f,q){db.memories(f).filter{q.isBlank()||it.title.contains(q,true)||it.body.contains(q,true)||it.tags.contains(q,true)}};Scaffold(topBar={Header("Memories")},floatingActionButton={AddFab{go(S.NewMemory(),T.Up)}},bottomBar={Nav(S.Memories,root)}){p->LazyColumn(Modifier.padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(3.dp),contentPadding=PaddingValues(bottom=96.dp)){item{OutlinedTextField(q,{q=it},Modifier.fillMaxWidth().height(56.dp),singleLine=true,shape=CircleShape,placeholder={Text("Search memories...")},leadingIcon={Icon(Icons.Rounded.Search,null)},trailingIcon={Icon(Icons.Rounded.Tune,null)})};item{Chips(listOf("All","Fixes","People","Ideas","Places"),f){f=it}};if(ms.isEmpty())item{Empty("No memories yet","Convert your best knowledge into something Future You can find.",Icons.Rounded.Bookmark)}else items(ms){m->Item(0,1,memoryIcon(m.type),m.title,"${m.type}${if(m.tags.isBlank())"" else " · ${m.tags}"}${m.revisitAt?.let{" · Revisit ${SimpleDateFormat("MMM d",Locale.getDefault()).format(Date(it))}"}?:""}"){go(S.Memory(m.id))}}}}}
private fun memoryIcon(t:String)=when(t){"Fix"->Icons.Rounded.Build;"Person"->Icons.Rounded.Person;"Place"->Icons.Rounded.Place;"Recipe"->Icons.Rounded.Restaurant;else->Icons.Rounded.Bookmark}

@Composable private fun MemoryDetail(db:MindRelayDb,id:Long,rev:Int,back:()->Unit,go:(S,T)->Unit,refresh:()->Unit){val m=db.memory(id)?:return;Scaffold(topBar={Header("Memory",back)}){p->Column(Modifier.verticalScroll(rememberScrollState()).padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Chips(listOf(m.type)+m.tags.split(" ").filter{it.isNotBlank()},m.type){};Text(m.title,style=MaterialTheme.typography.headlineSmallEmphasized,Modifier.fillMaxWidth(),textAlign=TextAlign.Center);CardX(body=m.body);Item(0,1,Icons.Rounded.FolderOpen,"Related project",m.projectId?.let{db.project(it)?.name}?:"None"){m.projectId?.let{go(S.Project(it))}};Item(0,1,Icons.Rounded.Schedule,"Source session",m.sourceSessionId?.let{db.session(it)?.title}?:"None"){m.sourceSessionId?.let{go(S.Session(it))}};Item(0,1,Icons.Rounded.EventRepeat,"Revisit",m.revisitAt?.let{SimpleDateFormat("MMM d, yyyy",Locale.getDefault()).format(Date(it))}?:"Not scheduled");OutlinedButton({db.archiveMemory(id);refresh();back()},Modifier.fillMaxWidth().height(56.dp),shape=RoundedCornerShape(28.dp)){Icon(Icons.Rounded.Archive,null);Spacer(Modifier.width(8.dp));Text("Archive")}}}}

@Composable private fun NewMemoryScreen(db:MindRelayDb,src:Long?,sess:Long?,back:()->Unit,go:(S,T)->Unit,refresh:()->Unit){var title by rememberSaveable{mutableStateOf("")};var type by rememberSaveable{mutableStateOf("Fix")};var body by rememberSaveable{mutableStateOf("")};var tags by rememberSaveable{mutableStateOf("")};var project by rememberSaveable{mutableLongStateOf(0)};var revisit by rememberSaveable{mutableStateOf("")};var menu by remember{mutableStateOf(false)};val projects=remember{db.projects()};val types=listOf("Fix","Person","Idea","Place","Recipe","Note","Other");Scaffold(topBar={Header("New Memory",back)}){p->Column(Modifier.verticalScroll(rememberScrollState()).padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){OutlinedTextField(title,{title=it},Modifier.fillMaxWidth(),label={Text("Title")},supportingText={Text("What will Future You search for?")});Box(Modifier.fillMaxWidth()){OutlinedTextField(type,{},Modifier.fillMaxWidth().clickable{menu=true},readOnly=true,label={Text("Type")},trailingIcon={Icon(Icons.Rounded.ExpandMore,null)});DropdownMenu(menu,{menu=false}){types.forEach{x->DropdownMenuItem({Text(x)},{type=x;menu=false})}}};OutlinedTextField(body,{body=it},Modifier.fillMaxWidth(),label={Text("Durable note")},minLines=5,supportingText={Text("Write it for Future You, not just Present You.")});OutlinedTextField(tags,{tags=it},Modifier.fillMaxWidth(),label={Text("Tags")});Item(0,1,Icons.Rounded.FolderOpen,"Linked project (optional)",projects.firstOrNull{it.id==project}?.name?:"None"){project=projects.firstOrNull()?.id?:0};Item(0,1,Icons.Rounded.EventRepeat,"Revisit date (optional)",revisit.ifBlank{"Not set"});Button(title.isNotBlank()&&body.isNotBlank(),{val n=db.insertMemory(title,type,body,tags,project.takeIf{it!=0L},src,sess,parseDate(revisit));src?.let{db.archiveCapture(it)};refresh();go(S.Memory(n),T.Right)},Modifier.fillMaxWidth().height(56.dp),shape=RoundedCornerShape(28.dp)){Text("Save Memory")}}}}

@Composable private fun NewProject(db:MindRelayDb,back:()->Unit,go:(S,T)->Unit){var n by rememberSaveable{mutableStateOf("")};var s by rememberSaveable{mutableStateOf("")};var a by rememberSaveable{mutableStateOf("")};var g by rememberSaveable{mutableStateOf("")};Scaffold(topBar={Header("New Project",back)}){p->Column(Modifier.verticalScroll(rememberScrollState()).padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){OutlinedTextField(n,{n=it},Modifier.fillMaxWidth(),label={Text("Project name")},supportingText={Text("Required")});OutlinedTextField(s,{s=it},Modifier.fillMaxWidth(),label={Text("Current state (optional)")});OutlinedTextField(a,{a=it},Modifier.fillMaxWidth(),label={Text("First / next action (optional)")});OutlinedTextField(g,{g=it},Modifier.fillMaxWidth(),label={Text("Goal / notes (optional)")},minLines=3);Button(n.isNotBlank(),{go(S.Project(db.insertProject(n,s,a,g)),T.Right)},Modifier.fillMaxWidth().height(56.dp),shape=RoundedCornerShape(28.dp)){Text("Create Project")}}}}

@Composable private fun Search(db:MindRelayDb,rev:Int,root:(S)->Unit,go:(S,T)->Unit,back:()->Unit){var q by rememberSaveable{mutableStateOf("")};var f by rememberSaveable{mutableStateOf("All")};val rs=remember(q,rev,f){db.search(q).filter{f=="All"||it.group==f}};Scaffold(topBar={Header("Search",back)},bottomBar={Nav(S.Search,root)}){p->LazyColumn(Modifier.padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(3.dp),contentPadding=PaddingValues(bottom=96.dp)){item{OutlinedTextField(q,{q=it},Modifier.fillMaxWidth().height(56.dp),singleLine=true,shape=CircleShape,placeholder={Text("pump timer")},leadingIcon={Icon(Icons.Rounded.Search,null)},trailingIcon={Icon(Icons.Rounded.Mic,null)})};item{Chips(listOf("All","Projects","Sessions","Memories"),f){f=it}};if(q.isBlank()||rs.isEmpty())item{Empty("Nothing found","Search across projects, sessions, memories, captures and tags.",Icons.Rounded.Search)}else rs.groupBy{it.group}.forEach{(g,xs)->item{Section(g)};items(xs){r->Item(0,1,searchIcon(r.icon),r.title,r.supporting){when(g){"Projects"->go(S.Project(r.id));"Sessions"->go(S.Session(r.id));"Memories"->go(S.Memory(r.id));"Captures"->go(S.Capture(r.id))}}}}}}}
private fun searchIcon(x:String)=when(x){"folder"->Icons.Rounded.FolderOpen;"schedule"->Icons.Rounded.Schedule;"bookmark"->Icons.Rounded.Bookmark;else->Icons.Rounded.Inbox}

@Composable private fun Settings(db:MindRelayDb,back:()->Unit,go:(S,T)->Unit,mode:String,setMode:(String)->Unit){var dlg by remember{mutableStateOf(false)};val ctx=LocalContext.current;val p=remember{ctx.getSharedPreferences("mindrelay",0)};var voice by remember{mutableStateOf(p.getBoolean("voice",true))};var link by remember{mutableStateOf(p.getBoolean("link",false))};var rem by remember{mutableStateOf(p.getBoolean("reminders",true))};Scaffold(topBar={Header("Settings",back)}){pad->Column(Modifier.verticalScroll(rememberScrollState()).padding(pad).padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Section("Appearance");Item(0,1,Icons.Rounded.Palette,"Theme",mode,{dlg=true});Item(0,1,Icons.Rounded.Brush,"Expressive style","Rounded · Roboto Flex");Section("Capture");Item(0,1,Icons.Rounded.Save,"Default save behavior","Save to Inbox");SwitchRow("Voice capture available",voice){voice=it;p.edit().putBoolean("voice",it).apply()};SwitchRow("Automatic project linking",link){link=it;p.edit().putBoolean("link",it).apply()};Section("Reminders");SwitchRow("Revisit reminders",rem){rem=it;p.edit().putBoolean("reminders",it).apply()};Section("Data");Item(0,1,Icons.Rounded.Storage,"Data & Backup","Local only · JSON export/import"){go(S.Backup)}};if(dlg)AlertDialog(onDismissRequest={dlg=false},title={Text("Theme")},text={Column{listOf("System","Light","Dark").forEach{x->TextButton({setMode(x);dlg=false},Modifier.fillMaxWidth()){Text(x)}}}},confirmButton={})}}
@Composable private fun SwitchRow(label:String,on:Boolean,set:(Boolean)->Unit)=Row(Modifier.fillMaxWidth().padding(vertical=6.dp),verticalAlignment=Alignment.CenterVertically){Text(label,Modifier.weight(1f));Switch(on,set)}

@Composable private fun Backup(db:MindRelayDb,back:()->Unit,refresh:()->Unit){val c=LocalContext.current;var preview by remember{mutableStateOf<String?>(null)};var msg by remember{mutableStateOf<String?>(null)};val save=rememberLauncherForActivityResult(ActivityResultContracts.CreateDocument("application/json")){u->if(u!=null)runCatching{c.contentResolver.openOutputStream(u)?.use{it.write(db.exportJson().toByteArray())}?:error("Unable to open destination")}.onSuccess{msg="Backup exported"}.onFailure{msg=it.message?:"Export failed"}};val open=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){u->if(u!=null)runCatching{c.contentResolver.openInputStream(u)?.bufferedReader()?.use{it.readText()}?:error("Unable to read backup")}.onSuccess{json->runCatching{JSONObject(json);preview=json}.onFailure{msg=it.message?:"Invalid backup"}}.onFailure{msg=it.message?:"Import failed"}};Scaffold(topBar={Header("Data & Backup",back)}){p->Column(Modifier.verticalScroll(rememberScrollState()).padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){CardX("Your data stays on your device","MindRelay stores everything locally in SQLite. There is no account, no cloud sync, and no silent upload. You own your data.",MaterialTheme.colorScheme.tertiaryContainer);Item(0,3,Icons.Rounded.FileDownload,"Export backup","Save projects, sessions, memories, captures, tasks to a file"){save.launch("mindrelay-backup.json")};Item(1,3,Icons.Rounded.FileUpload,"Import backup","Validate schema before merging"){open.launch(arrayOf("application/json","text/plain"))};Item(2,3,Icons.Rounded.Restore,"Restore from backup","Preview before replacing data"){open.launch(arrayOf("application/json","text/plain"))};Section("Backup includes");Text("""• Projects & current state
• Sessions & chronological entries
• Memories with tags and revisit dates
• Captures with provenance
• Tasks
• All relationships and metadata""");Text("Keystore-backed encrypted exports, app lock, biometric unlock.",style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)}};if(preview!=null)AlertDialog(onDismissRequest={preview=null},title={Text("Backup preview")},text={Text("Schema valid. Ready to import.")},confirmButton={Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){TextButton({val result=db.importJson(preview!!,false);msg=result.second;refresh();preview=null}){Text("Merge")};Button({val result=db.importJson(preview!!,true);msg=result.second;refresh();preview=null}){Text("Replace")}}},dismissButton={TextButton({preview=null}){Text("Cancel")}});if(msg!=null)AlertDialog(onDismissRequest={msg=null},text={Text(msg!!)},confirmButton={TextButton({msg=null}){Text("OK")}})}

private fun ago(x:Long)=when(val m=(System.currentTimeMillis()-x).coerceAtLeast(0)/60000){in 0..0->"just now";in 1..59->"$m min ago";in 60..1439->"${m/60} hour${if(m/60==1L)""else"s"} ago";in 1440..2879->"yesterday";else->"${m/1440} days ago"}
private fun duration(s:Long,e:Long?):String{val m=((e?:System.currentTimeMillis())-s).coerceAtLeast(0)/60000;return "${m/60}h ${m%60}m"}
private fun parseDate(x:String)=runCatching{SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).parse(x.trim())?.time}.getOrNull()
